create table if not exists public."BASE DE DATOS ESCUELAS SLEP" (
  "N°" bigint primary key,
  "RBD" text,
  "NOMBRE ESTABLECIMIENTO" text,
  "COMUNA" text,
  "REPRESENTANTE CONSEJO ESCOLAR" text,
  "CORREO REPRESENTANTE" text,
  "ASESOR UATP" text,
  "CORREO ASESOR" text,
  "DIRECCIÓN" text,
  "COMUNA_1" text,
  "RURAL/URBANO" text,
  "DIRECTOR/A" text,
  "RUT" text,
  "TELEFONO FIJO/ANEXOS" text,
  "TELEFONO CELULAR" text,
  "CORREO ELECTRÓNICO" text,
  "CORREO SUBROGANTE" text,
  "FUNCIONARIO SUBROGANTE POR LM" text,
  "CELULAR" text,
  "OBSERVACIONES" text,
  "TIPO" text,
  "NOMBRE PRESIDENTE CGPMA" text,
  "CORREO" text,
  "TELEFONO" text,
  "OBSERVACION CGPMA" text,
  "LATITUD" text,
  "LONGITUD" text,
  "ALTITUD" text
);